version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '3001:3001'
    networks:
      - webnet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:80'  # React build served via NGINX
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - webnet

networks:
  webnet:
